version: '3.5'

services:
    mysql_crypto_currency:
        image: mysql:5.7
        container_name: mysql_crypto_currency
        ports:
            - "${DATABASE_EXTERNAL_PORT}:3306"
        environment:
            MYSQL_DATABASE: "${DATABASE_NAME}"
            MYSQL_USER: "${DATABASE_USER}"
            MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - crypto-currency

    php_fpm:
        image: php:8.1-fpm
        container_name: php_fpm
        build:
            context: .
            dockerfile: ./docker/fpm/Dockerfile
        volumes:
            - ./:/var/www/symfony
        networks:
            - crypto-currency

    nginx_crypto_currency:
        container_name: nginx_crypto_currency
        build:
            context: ./docker/nginx
        volumes:
            - ./:/var/www/symfony
            - ./docker/nginx/nginx-conf.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs/:/var/log/nginx:cached
        ports:
            - "8088:80"
        depends_on:
            - php_fpm
        networks:
            - crypto-currency

networks:
    crypto-currency:

volumes:
    db-data:
        name: db-data
